### ISSUE TITLE
Storybook errors

### ISSUE THREAD

**Issue by samuelhorn** [prismicio-community/slice-library-starter-nuxt#1]
Already started on a slice library but thought its better to remake it from your starter :)

Followed the setup instructions 100% (with yarn & node 14.4.0) but Storybook is blank and shows a react error in console as follows, also worth to note is that if I install slicemachine on a blank nuxt project on my system storybook works great if thats a hint. Also, sm-ui pulls the screenshot of the component and storybook seems to run fine and update in terminal, just in browser it wont work.:

```
vendors~main.4473f90fd7e61a23c0e4.bundle.js:67618 The above error occurred in the <Context.Consumer> component:
    in Styled(div)
    in div
    in Styled(div)
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer (created by Panel)
    in Panel (created by Layout)
    in div
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div
    in Styled(div) (created by Main)
    in div
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout)
    in Unknown
    in div
    in Styled(div)
    in Unknown (created by SizeMeRenderer(Component))
    in SizeMeReferenceWrapper (created by SizeMeRenderer(Component))
    in SizeMeRenderer(Component) (created by SizeMe(Component))
    in SizeMe(Component)
    in ThemeProvider
    in Unknown (created by ManagerConsumer)
    in ManagerConsumer (created by Manager)
    in EffectOnMount (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
logCapturedError @ vendors~main.4473f90fd7e61a23c0e4.bundle.js:67618
vendors~main.4473f90fd7e61a23c0e4.bundle.js:67618 The above error occurred in the <LocationProvider> component:
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by lihbr** [comment]
Suggested quick patch: delete lock file & run yarn again.

I'm investigating for a way to prevent this issue.

**Comment by lihbr** [comment]
Updated the lock file in 6c7db22, should be good now. This is getting me confused about should I version the `yarn.lock` file... I'll close the issue for now, feel free to reopen if any comment ☺️

**Comment by samuelhorn** [comment]
@lihbr, I feel you. It's a constant struggle versioning lock-files. :) But yeah, it should be [done](https://classic.yarnpkg.com/en/docs/yarn-lock/)!

"All yarn.lock files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server."
